// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function ApplyVietnameseImePatch():Promise<services.PatchResult>;

export function CheckVietnameseImePatchStatus():Promise<services.PatchStatus>;

export function ClearTerminalBacklog(arg1:string):Promise<Record<string, any>>;

export function DeleteValue(arg1:string):Promise<Record<string, any>>;

export function GetAppVersion():Promise<string>;

export function GetCwd():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetTerminalBacklog(arg1:string):Promise<Record<string, any>>;

export function GetTerminalStatus(arg1:string):Promise<Record<string, any>>;

export function GetValue(arg1:string):Promise<any>;

export function GetVietnameseImeSettings():Promise<services.IMESettings>;

export function KillTerminal(arg1:string):Promise<Record<string, any>>;

export function ListDirectory(arg1:string):Promise<services.DirectoryListing>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function RestoreVietnameseImePatch():Promise<services.RestoreResult>;

export function SetValue(arg1:string,arg2:any):Promise<Record<string, any>>;

export function SetVietnameseImeSettings(arg1:services.IMESettings):Promise<services.Result>;

export function SetWorkspaceActive(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function ShowOpenDialog(arg1:services.DialogOptions):Promise<services.DialogResult>;

export function SpawnTerminal(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<Record<string, any>>;

export function SpawnTerminalWithAgent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<Record<string, any>>;

export function ValidateVietnameseImePatch():Promise<services.PatchValidation>;

export function WindowClose():Promise<void>;

export function WindowIsMaximized():Promise<boolean>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<Record<string, any>>;
