// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyVietnameseImePatch() {
  return window['go']['main']['App']['ApplyVietnameseImePatch']();
}

export function CheckVietnameseImePatchStatus() {
  return window['go']['main']['App']['CheckVietnameseImePatchStatus']();
}

export function ClearTerminalBacklog(arg1) {
  return window['go']['main']['App']['ClearTerminalBacklog'](arg1);
}

export function DeleteValue(arg1) {
  return window['go']['main']['App']['DeleteValue'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCwd() {
  return window['go']['main']['App']['GetCwd']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetTerminalBacklog(arg1) {
  return window['go']['main']['App']['GetTerminalBacklog'](arg1);
}

export function GetTerminalStatus(arg1) {
  return window['go']['main']['App']['GetTerminalStatus'](arg1);
}

export function GetValue(arg1) {
  return window['go']['main']['App']['GetValue'](arg1);
}

export function GetVietnameseImeSettings() {
  return window['go']['main']['App']['GetVietnameseImeSettings']();
}

export function KillTerminal(arg1) {
  return window['go']['main']['App']['KillTerminal'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestoreVietnameseImePatch() {
  return window['go']['main']['App']['RestoreVietnameseImePatch']();
}

export function SetValue(arg1, arg2) {
  return window['go']['main']['App']['SetValue'](arg1, arg2);
}

export function SetVietnameseImeSettings(arg1) {
  return window['go']['main']['App']['SetVietnameseImeSettings'](arg1);
}

export function SetWorkspaceActive(arg1, arg2) {
  return window['go']['main']['App']['SetWorkspaceActive'](arg1, arg2);
}

export function ShowOpenDialog(arg1) {
  return window['go']['main']['App']['ShowOpenDialog'](arg1);
}

export function SpawnTerminal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SpawnTerminal'](arg1, arg2, arg3, arg4, arg5);
}

export function SpawnTerminalWithAgent(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SpawnTerminalWithAgent'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ValidateVietnameseImePatch() {
  return window['go']['main']['App']['ValidateVietnameseImePatch']();
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsMaximized() {
  return window['go']['main']['App']['WindowIsMaximized']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}
