// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DB represents a collection of key-value pairs that persist on disk.
 * Transactions are used for all forms of data access to the DB.
 */
export class DB {
    /**
     * Creates a new DB instance.
     * @param {Partial<DB>} [$$source = {}] - The source object to create the DB.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DB instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DB}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DB(/** @type {Partial<DB>} */($$parsedSource));
    }
}
