// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['services']['StoreService']['Close']();
}

export function DeleteByPrefix(arg1) {
  return window['go']['services']['StoreService']['DeleteByPrefix'](arg1);
}

export function DeleteValue(arg1) {
  return window['go']['services']['StoreService']['DeleteValue'](arg1);
}

export function GetByPrefix(arg1) {
  return window['go']['services']['StoreService']['GetByPrefix'](arg1);
}

export function GetDB() {
  return window['go']['services']['StoreService']['GetDB']();
}

export function GetRaw(arg1) {
  return window['go']['services']['StoreService']['GetRaw'](arg1);
}

export function GetValue(arg1) {
  return window['go']['services']['StoreService']['GetValue'](arg1);
}

export function SetRaw(arg1, arg2) {
  return window['go']['services']['StoreService']['SetRaw'](arg1, arg2);
}

export function SetValue(arg1, arg2) {
  return window['go']['services']['StoreService']['SetValue'](arg1, arg2);
}
