// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {buntdb} from '../models';

export function Close():Promise<void>;

export function DeleteByPrefix(arg1:string):Promise<void>;

export function DeleteValue(arg1:string):Promise<services.Result>;

export function GetByPrefix(arg1:string):Promise<Record<string, any>>;

export function GetDB():Promise<buntdb.DB>;

export function GetRaw(arg1:string):Promise<string>;

export function GetValue(arg1:string):Promise<any>;

export function SetRaw(arg1:string,arg2:string):Promise<void>;

export function SetValue(arg1:string,arg2:any):Promise<services.Result>;
