// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['services']['SystemService']['GetAppVersion']();
}

export function GetCwd() {
  return window['go']['services']['SystemService']['GetCwd']();
}

export function GetEnv(arg1) {
  return window['go']['services']['SystemService']['GetEnv'](arg1);
}

export function GetPlatform() {
  return window['go']['services']['SystemService']['GetPlatform']();
}

export function GetShellInfo() {
  return window['go']['services']['SystemService']['GetShellInfo']();
}

export function ListDirectory(arg1) {
  return window['go']['services']['SystemService']['ListDirectory'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['services']['SystemService']['OpenExternal'](arg1);
}

export function ShowOpenDialog(arg1) {
  return window['go']['services']['SystemService']['ShowOpenDialog'](arg1);
}
