// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function GetAppVersion():Promise<string>;

export function GetCwd():Promise<string>;

export function GetEnv(arg1:string):Promise<string>;

export function GetPlatform():Promise<string>;

export function GetShellInfo():Promise<Record<string, string>>;

export function ListDirectory(arg1:string):Promise<services.DirectoryListing>;

export function OpenExternal(arg1:string):Promise<void>;

export function ShowOpenDialog(arg1:services.DialogOptions):Promise<services.DialogResult>;
