// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function DeleteTemplate(arg1:string):Promise<services.Result>;

export function GetTemplates():Promise<Array<services.Template>>;

export function Init(arg1:services.StoreService):Promise<void>;

export function SaveTemplate(arg1:services.Template):Promise<services.Template>;
