// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTemplate(arg1) {
  return window['go']['services']['TemplateService']['DeleteTemplate'](arg1);
}

export function GetTemplates() {
  return window['go']['services']['TemplateService']['GetTemplates']();
}

export function Init(arg1) {
  return window['go']['services']['TemplateService']['Init'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['services']['TemplateService']['SaveTemplate'](arg1);
}
