// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistoryEntry(arg1, arg2) {
  return window['go']['services']['TerminalHistoryService']['AddHistoryEntry'](arg1, arg2);
}

export function ClearTerminalHistory(arg1) {
  return window['go']['services']['TerminalHistoryService']['ClearTerminalHistory'](arg1);
}

export function GetTerminalHistory(arg1) {
  return window['go']['services']['TerminalHistoryService']['GetTerminalHistory'](arg1);
}

export function Init(arg1) {
  return window['go']['services']['TerminalHistoryService']['Init'](arg1);
}

export function SaveTerminalHistory(arg1, arg2) {
  return window['go']['services']['TerminalHistoryService']['SaveTerminalHistory'](arg1, arg2);
}
