// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupAllTerminals() {
  return window['go']['services']['TerminalService']['CleanupAllTerminals']();
}

export function CleanupWorkspaceTerminals(arg1) {
  return window['go']['services']['TerminalService']['CleanupWorkspaceTerminals'](arg1);
}

export function ClearTerminalBacklog(arg1) {
  return window['go']['services']['TerminalService']['ClearTerminalBacklog'](arg1);
}

export function GetTerminalBacklog(arg1) {
  return window['go']['services']['TerminalService']['GetTerminalBacklog'](arg1);
}

export function GetTerminalStatus(arg1) {
  return window['go']['services']['TerminalService']['GetTerminalStatus'](arg1);
}

export function IsWorkspaceActive(arg1) {
  return window['go']['services']['TerminalService']['IsWorkspaceActive'](arg1);
}

export function KillTerminal(arg1) {
  return window['go']['services']['TerminalService']['KillTerminal'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['services']['TerminalService']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['services']['TerminalService']['SetContext'](arg1);
}

export function SetWorkspaceActive(arg1, arg2) {
  return window['go']['services']['TerminalService']['SetWorkspaceActive'](arg1, arg2);
}

export function SpawnTerminal(arg1) {
  return window['go']['services']['TerminalService']['SpawnTerminal'](arg1);
}

export function SpawnTerminalWithAgent(arg1) {
  return window['go']['services']['TerminalService']['SpawnTerminalWithAgent'](arg1);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['services']['TerminalService']['WriteToTerminal'](arg1, arg2);
}
