// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function AddHistoryEntry(arg1:string,arg2:string):Promise<services.Result>;

export function ClearTerminalHistory(arg1:string):Promise<services.Result>;

export function GetTerminalHistory(arg1:string):Promise<Array<services.HistoryEntry>>;

export function Init(arg1:services.StoreService):Promise<void>;

export function SaveTerminalHistory(arg1:string,arg2:Array<services.HistoryEntry>):Promise<services.Result>;
