// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CleanupAllTerminals():Promise<services.CleanupResult>;

export function CleanupWorkspaceTerminals(arg1:string):Promise<services.CleanupResult>;

export function ClearTerminalBacklog(arg1:string):Promise<void>;

export function GetTerminalBacklog(arg1:string):Promise<string>;

export function GetTerminalStatus(arg1:string):Promise<Record<string, any>>;

export function IsWorkspaceActive(arg1:string):Promise<boolean>;

export function KillTerminal(arg1:string):Promise<services.KillResult>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<services.Result>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetWorkspaceActive(arg1:string,arg2:boolean):Promise<void>;

export function SpawnTerminal(arg1:services.SpawnTerminalOptions):Promise<services.SpawnResult>;

export function SpawnTerminalWithAgent(arg1:services.SpawnAgentOptions):Promise<services.SpawnResult>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<services.Result>;
