// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function ApplyVietnameseImePatch():Promise<services.PatchResult>;

export function FindClaudePath():Promise<string>;

export function GetCurrentClaudeVersion():Promise<string>;

export function GetIMESettings():Promise<services.IMESettings>;

export function GetPatchStatus():Promise<services.PatchStatus>;

export function Init(arg1:services.StoreService):Promise<void>;

export function IsVietnameseImePatched():Promise<boolean>;

export function KillClaudeProcesses():Promise<services.KillClaudeProcessesResult>;

export function RestoreFromBackup():Promise<services.RestoreResult>;

export function SaveIMESettings(arg1:services.IMESettings):Promise<services.Result>;

export function ValidatePatch():Promise<services.PatchValidation>;
