// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyVietnameseImePatch() {
  return window['go']['services']['VietnameseIMEService']['ApplyVietnameseImePatch']();
}

export function FindClaudePath() {
  return window['go']['services']['VietnameseIMEService']['FindClaudePath']();
}

export function GetCurrentClaudeVersion() {
  return window['go']['services']['VietnameseIMEService']['GetCurrentClaudeVersion']();
}

export function GetIMESettings() {
  return window['go']['services']['VietnameseIMEService']['GetIMESettings']();
}

export function GetPatchStatus() {
  return window['go']['services']['VietnameseIMEService']['GetPatchStatus']();
}

export function Init(arg1) {
  return window['go']['services']['VietnameseIMEService']['Init'](arg1);
}

export function IsVietnameseImePatched() {
  return window['go']['services']['VietnameseIMEService']['IsVietnameseImePatched']();
}

export function KillClaudeProcesses() {
  return window['go']['services']['VietnameseIMEService']['KillClaudeProcesses']();
}

export function RestoreFromBackup() {
  return window['go']['services']['VietnameseIMEService']['RestoreFromBackup']();
}

export function SaveIMESettings(arg1) {
  return window['go']['services']['VietnameseIMEService']['SaveIMESettings'](arg1);
}

export function ValidatePatch() {
  return window['go']['services']['VietnameseIMEService']['ValidatePatch']();
}
