// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CreateWorkspace(arg1:services.Workspace):Promise<services.Workspace>;

export function DeleteWorkspace(arg1:string):Promise<services.Result>;

export function GetWorkspace(arg1:string):Promise<services.Workspace>;

export function GetWorkspaces():Promise<Array<services.Workspace>>;

export function Init(arg1:services.StoreService,arg2:services.TerminalService):Promise<void>;

export function PatchWorkspace(arg1:string,arg2:Record<string, any>):Promise<services.Workspace>;

export function UpdateWorkspace(arg1:services.Workspace):Promise<services.Workspace>;
