// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWorkspace(arg1) {
  return window['go']['services']['WorkspaceService']['CreateWorkspace'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['services']['WorkspaceService']['DeleteWorkspace'](arg1);
}

export function GetWorkspace(arg1) {
  return window['go']['services']['WorkspaceService']['GetWorkspace'](arg1);
}

export function GetWorkspaces() {
  return window['go']['services']['WorkspaceService']['GetWorkspaces']();
}

export function Init(arg1, arg2) {
  return window['go']['services']['WorkspaceService']['Init'](arg1, arg2);
}

export function PatchWorkspace(arg1, arg2) {
  return window['go']['services']['WorkspaceService']['PatchWorkspace'](arg1, arg2);
}

export function UpdateWorkspace(arg1) {
  return window['go']['services']['WorkspaceService']['UpdateWorkspace'](arg1);
}
